### ISSUE TITLE
CSIの取得について

### ISSUE THREAD

**Issue by t5670116** [SK-eee-ku/csi_realtime_plot#1]
初めまして、研究の兼ね合いでnexmonを利用したCSIの取得を行いたいのですがうまくいかず相談にのっていただければと思います。
raspberry piにnexmonを導入しCSIを取得する場合はraspberry piがwi-fiで接続しているルーターとの通信のCSIを取得しているとの認識でお間違いないでしょうか。
その際ルーター側で何か作業しないといけないことはありますでしょうか。
お忙しいところ恐縮ですが回答していただけると幸いです。

**Comment by SabaNoMisoni1123** [comment]
質問に対して回答させていただきます．
nexmonを導入したrasberry piは接続関係のない端末の信号を勝手に傍受する形で受信し，そこからCSIを推定・出力する動作をしております．
実際の実験の例としましては，アクセスポイントにスマホを接続し，動画視聴などをしてアクセスポイントがフレーム送信する環境を作ってあげて，
そこでnexmon導入済みraspberry piを動作させることでCSIを取得することができます．

raspberry piは送受信局間のフレームを傍受する形でCSIを取得しますので，ルータとの接続は不要です．

2022年6月22日(水) 11:38 T5670116 ***@***.***>:

**Comment by t5670116** [comment]
迅速な質問対応誠に感謝します。
nexliveコマンドによってアクセスポイントに接続されているスマートフォン端末をMacアドレスによって指定しているとの解釈でお間違いないでしょうか？

またアクセスポイントを送信機、nexmonを導入したraspberry pi受信機とした通信のCSIを取得することはできないとの認識であっていますでしょうか？
私の目的はAsus RT-AC86Uのルーター二つの通信のCSIを取得です。その方法として現在nexmonsterに記載のあるAsus RT-AC86Uにファームウェアを書き込みCSIを取得する方法を考えているのですがファームウェアをインストールした端末を受信機とすることはできないのでしょうか？

お忙しいところ恐縮ですが回答していただけると幸いです。
よろしくお願いいたします。

**Comment by SabaNoMisoni1123** [comment]
> nexliveコマンドによってアクセスポイントに接続されているスマートフォン端末をMacアドレスによって指定しているとの解釈でお間違いないでしょうか？

正しいです．厳密にはスマートフォンのMACアドレス，またはアクセスポイントのMACアドレスを指定できます．指定のない場合は両者のCSIを取得された順で図示します．

> またアクセスポイントを送信機、nexmonを導入したraspberry pi受信機とした通信のCSIを取得することはできないとの認識であっていますでしょうか？

raspberry piでアクセスポイントのCSIを取得することは可能です．先の回答で「接続関係のない端末の信号」からCSIを推定すると申しましたが，誤解を与えてしまい申し訳ありません．nexmon csiはフレームを送信する送信局（端末，APなど）とnexmon csi導入済み端末との間のCSIを取得します．

> 私の目的はAsus RT-AC86Uのルーター二つの通信のCSIを取得です。その方法として現在nexmonsterに記載のあるAsus RT-AC86Uにファームウェアを書き込みCSIを取得する方法を考えているのですがファームウェアをインストールした端末を受信機とすることはできないのでしょうか？

このような実験の実現には少なくとももう1台の通信端末が必要です．以下の手順で所望のCSIが取得されるでしょう．
1. nexmon csi非導入ルータと何らかの通信端末を無線接続する．
2. nexmon csi非導入ルータから端末への下り通信を発生させる．
3. nexmon csi導入ルータは非導入ルータのMACアドレスを指定して動作させる．
nexmon csi非導入ルータと導入ルータとの間には接続の関係はありません．

**Comment by t5670116** [comment]
何度も質問に受け答えしていただき誠にありがとうございます。
ご教授いただいた方法にて取得を試みたいと思います。

> 正しいです．厳密にはスマートフォンのMACアドレス，またはアクセスポイントのMACアドレスを指定できます．指定のない場合は両者のCSIを取得された順で図示します．

MACアドレスを指定していない際の処理なのですがアクセスポイントとスマートフォン端末以外にも周りで通信が行われていたらそれらのCSIも取得するといった認識でお間違いないでしょうか？
つまり複数のアクセスポイント、複数のステーション端末が環境内にあればそれらすべての送信局とのCSIが取得できるということでしょうか？

また、 @SK-eee-ku 様がこのgithubにて紹介なさっているリアルタイムのCSI取得ツールであるnexliveはAsus RT-AC86Uにも適応可能でしょうか？
ご意見をお聞かせいただければ幸いです。

お忙しいところ恐縮ですが回答していただけると幸いです。
よろしくお願いいたします。

**Comment by SabaNoMisoni1123** [comment]
> MACアドレスを指定していない際の処理なのですがアクセスポイントとスマートフォン端末以外にも周りで通信が行われていたらそれらのCSIも取得するといった認識でお間違いないでしょうか？
つまり複数のアクセスポイント、複数のステーション端末が環境内にあればそれらすべての送信局とのCSIが取得できるということでしょうか？

試したことはございませんが，おっしゃるとおりであると思われます．同じ周波数帯域で通信するすべての送信局からCSIが収集されるはずです．

> また、 @SK-eee-ku 様がこのgithubにて紹介なさっているリアルタイムのCSI取得ツールであるnexliveはAsus RT-AC86Uにも適応可能でしょうか？

正直に申し上げて厳しいのではないかと思います．アクセスポイント機器に本プログラムの実行環境が構築できるのか全く分からないためです．
もし，Asus RT-AC86Uに適応ができた場合，プルリクエストを送っていただけると幸いです．
